using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.InteropServices;

namespace CSTD.USER
{
    public enum KEY
    {
        LMOUSE,
        RMOUSE,
        CANCEL,
        MMOUSE,
        X1MOUSE,
        X2MOUSE,
        BACKSPACE,
        TAB,
        CLEAR,
        RETURN,
        SHIFT,
        CONTROL,
        ALT,
        PAUSE,
        CAPSLOCK,
        ESCAPE,
        SPACEBAR,
        PAGEUP,
        PAGEDOWN,
        END,
        HOME,
        LEFT,
        UP,
        RIGHT,
        DOWN,
        SELECT,
        PRINT,
        PRINTSCREEN,
        INSERT,
        DELETE,
        HELP,
        ZERO,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX,
        SEVEN,
        EIGHT,
        NINE,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LWIN,
        RWIN,
        APPS,
        SLEEP,
        NUMPAD0,
        NUMPAD1,
        NUMPAD2,
        NUMPAD3,
        NUMPAD4,
        NUMPAD5,
        NUMPAD6,
        NUMPAD7,
        NUMPAD8,
        NUMPAD9,
        MULTIPLY,
        ADD,
        SEPARATOR,
        SUBTRACT,
        DECIMAL,
        DIVIDE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        NUMLOCK,
        SCROLLLOCK,
        LSHIFT,
        RSHIFT,
        LCONTROL,
        RCONTROL,
        LALT,
        RALT,
        BROWSERBACK,
        BROWSERFORWARD,
        BROWSERREFRESH,
        BROWSERSTOP,
        BROWSERSEARCH,
        BROWSERFAVORITES,
        BROWSERHOME,
        VOLUMEMUTE,
        VOLUMEDOWN,
        VOLUMEUP,
        NEXTTRACK,
        PREVIOUSTRACK,
        STOPMEDIA,
        PLAYPAUSEMEDIA,
        MAIL,
        MEDIASELECT,
        APP1,
        APP2,
        PLUS,
        COMMA,
        MINUS,
        DOT,
        PACKET,
        ATTN,
        CRSEL,
        EXSEL,
        ERASEEOF,
        PLAY,
        ZOOM,
        PA1,
        OEMCLEAR
    }

    public class keyboard
    {
        static Dictionary<KEY, byte> vk = new Dictionary<KEY, byte>()
        {
            { KEY.LMOUSE, 0x01 },
            { KEY.RMOUSE, 0x02 },
            { KEY.CANCEL, 0x03 },
            { KEY.MMOUSE, 0x04 },
            { KEY.X1MOUSE, 0x05 },
            { KEY.X2MOUSE, 0x06 },
            { KEY.BACKSPACE, 0x08 },
            { KEY.TAB, 0x09 },
            { KEY.CLEAR, 0x0C },
            { KEY.RETURN, 0x0D },
            { KEY.SHIFT, 0x10 },
            { KEY.CONTROL, 0x11 },
            { KEY.ALT, 0x12 },
            { KEY.PAUSE, 0x13 },
            { KEY.CAPSLOCK, 0x14 },
            { KEY.ESCAPE, 0x1B },
            { KEY.SPACEBAR, 0x20 },
            { KEY.PAGEUP, 0x21 },
            { KEY.PAGEDOWN, 0x22 },
            { KEY.END, 0x23 },
            { KEY.HOME, 0x24 },
            { KEY.LEFT, 0x25 },
            { KEY.UP, 0x26 },
            { KEY.RIGHT, 0x27 },
            { KEY.DOWN, 0x28 },
            { KEY.SELECT, 0x29 },
            { KEY.PRINT, 0x2A },
            { KEY.PRINTSCREEN, 0x2C },
            { KEY.INSERT, 0x2D },
            { KEY.DELETE, 0x2E },
            { KEY.HELP, 0x2F },
            { KEY.ZERO, 0x30 },
            { KEY.ONE, 0x31 },
            { KEY.TWO, 0x32 },
            { KEY.THREE, 0x33 },
            { KEY.FOUR, 0x34 },
            { KEY.FIVE, 0x35 },
            { KEY.SIX, 0x36 },
            { KEY.SEVEN, 0x37 },
            { KEY.EIGHT, 0x38 },
            { KEY.NINE, 0x39 },
            { KEY.A, 0x41 },
            { KEY.B, 0x42 },
            { KEY.C, 0x43 },
            { KEY.D, 0x44 },
            { KEY.E, 0x45 },
            { KEY.F, 0x46 },
            { KEY.G, 0x47 },
            { KEY.H, 0x48 },
            { KEY.I, 0x49 },
            { KEY.J, 0x4A },
            { KEY.K, 0x4B },
            { KEY.L, 0x4C },
            { KEY.M, 0x4D },
            { KEY.N, 0x4E },
            { KEY.O, 0x4F },
            { KEY.P, 0x50 },
            { KEY.Q, 0x51 },
            { KEY.R, 0x52 },
            { KEY.S, 0x53 },
            { KEY.T, 0x54 },
            { KEY.U, 0x55 },
            { KEY.V, 0x56 },
            { KEY.W, 0x57 },
            { KEY.X, 0x58 },
            { KEY.Y, 0x59 },
            { KEY.Z, 0x5A },
            { KEY.LWIN, 0x5B },
            { KEY.RWIN, 0x5C },
            { KEY.APPS, 0x5D },
            { KEY.SLEEP, 0x5F },
            { KEY.NUMPAD0, 0x60 },
            { KEY.NUMPAD1, 0x61 },
            { KEY.NUMPAD2, 0x62 },
            { KEY.NUMPAD3, 0x63 },
            { KEY.NUMPAD4, 0x64 },
            { KEY.NUMPAD5, 0x65 },
            { KEY.NUMPAD6, 0x66 },
            { KEY.NUMPAD7, 0x67 },
            { KEY.NUMPAD8, 0x68 },
            { KEY.NUMPAD9, 0x69 },
            { KEY.MULTIPLY, 0x6A },
            { KEY.ADD, 0x6B },
            { KEY.SEPARATOR, 0x6C },
            { KEY.SUBTRACT, 0x6D },
            { KEY.DECIMAL, 0x6E },
            { KEY.DIVIDE, 0x6F },
            { KEY.F1, 0x70 },
            { KEY.F2, 0x71 },
            { KEY.F3, 0x72 },
            { KEY.F4, 0x73 },
            { KEY.F5, 0x74 },
            { KEY.F6, 0x75 },
            { KEY.F7, 0x76 },
            { KEY.F8, 0x77 },
            { KEY.F9, 0x78 },
            { KEY.F10, 0x79 },
            { KEY.F11, 0x7A },
            { KEY.F12, 0x7B },
            { KEY.F13, 0x7C },
            { KEY.F14, 0x7D },
            { KEY.F15, 0x7E },
            { KEY.F16, 0x7F },
            { KEY.F17, 0x80 },
            { KEY.F18, 0x81 },
            { KEY.F19, 0x82 },
            { KEY.F20, 0x83 },
            { KEY.F21, 0x84 },
            { KEY.F22, 0x85 },
            { KEY.F23, 0x86 },
            { KEY.F24, 0x87 },
            { KEY.NUMLOCK, 0x90 },
            { KEY.SCROLLLOCK, 0x91 },
            { KEY.LSHIFT, 0xA0 },
            { KEY.RSHIFT, 0xA1 },
            { KEY.LCONTROL, 0xA2 },
            { KEY.RCONTROL, 0xA3 },
            { KEY.LALT, 0xA4 },
            { KEY.RALT, 0xA5 },
            { KEY.BROWSERBACK, 0xA6 },
            { KEY.BROWSERFORWARD, 0xA7 },
            { KEY.BROWSERREFRESH, 0xA8 },
            { KEY.BROWSERSTOP, 0xA9 },
            { KEY.BROWSERSEARCH, 0xAA },
            { KEY.BROWSERFAVORITES, 0xAB },
            { KEY.BROWSERHOME, 0xAC },
            { KEY.VOLUMEMUTE, 0xAD },
            { KEY.VOLUMEDOWN, 0xAE },
            { KEY.VOLUMEUP, 0xAF },
            { KEY.NEXTTRACK, 0xB0 },
            { KEY.PREVIOUSTRACK, 0xB1 },
            { KEY.STOPMEDIA, 0xB2 },
            { KEY.PLAYPAUSEMEDIA, 0xB3 },
            { KEY.MAIL, 0xB4 },
            { KEY.MEDIASELECT, 0xB5 },
            { KEY.APP1, 0xB6 },
            { KEY.APP2, 0xB7 },
            { KEY.PLUS, 0xBB },
            { KEY.COMMA, 0xBC },
            { KEY.MINUS, 0xBD },
            { KEY.DOT, 0xBE },
            { KEY.PACKET, 0xE7 },
            { KEY.ATTN, 0xF6 },
            { KEY.CRSEL, 0xF7 },
            { KEY.EXSEL, 0xF8 },
            { KEY.ERASEEOF, 0xF9 },
            { KEY.PLAY, 0xFA },
            { KEY.ZOOM, 0xFB },
            { KEY.PA1, 0xFD },
            { KEY.OEMCLEAR, 0xFE }
        };

        static Dictionary<KEY, byte> scan_make = new Dictionary<KEY, byte>()
        {
            { KEY.LMOUSE,
            { KEY.RMOUSE,
            { KEY.CANCEL,
            { KEY.MMOUSE,
            { KEY.X1MOUSE,
            { KEY.X2MOUSE,
            { KEY.BACKSPACE, 0x0E },
            { KEY.TAB, 0x0F },
            { KEY.CLEAR,
            { KEY.RETURN, 0x1C },
            { KEY.SHIFT,
            { KEY.CONTROL,
            { KEY.ALT,
            { KEY.PAUSE,
            { KEY.CAPSLOCK, 0x3A },
            { KEY.ESCAPE, 0x01 },
            { KEY.SPACEBAR, 0x39
            { KEY.PAGEUP, 0x49
            { KEY.END, 0x4F },
            { KEY.HOME,
            { KEY.LEFT,
            { KEY.UP,
            { KEY.RIGHT,
            { KEY.DOWN,
            { KEY.SELECT,
            { KEY.PRINT, 0x00
            { KEY.PRINTSCREEN,
            { KEY.INSERT,
            { KEY.DELETE,
            { KEY.HELP,
            { KEY.ZERO, 0x0B }
            { KEY.ONE, 0x02 },
            { KEY.TWO, 0x03 },
            { KEY.THREE, 0x04 },
            { KEY.FOUR, 0x05 },
            { KEY.FIVE, 0x06 },
            { KEY.SIX, 0x07 },
            { KEY.SEVEN, 0x08 },
            { KEY.EIGHT, 0x09 },
            { KEY.NINE, 0x0A },
            { KEY.A, 0x1E },
            { KEY.B, 0x30 },
            { KEY.C, 0x2E },
            { KEY.D, 0x20 },
            { KEY.E, 0x12 },
            { KEY.F, 0x21 },
            { KEY.G, 0x22 },
            { KEY.H, 0x23 },
            { KEY.I, 0x17 },
            { KEY.J, 0x24 },
            { KEY.K, 0x25 },
            { KEY.L, 0x26 },
            { KEY.M, 0x32 },
            { KEY.N, 0x31 },
            { KEY.O, 0x18 },
            { KEY.P, 0x19 },
            { KEY.Q, 0x10 },
            { KEY.R, 0x13 },
            { KEY.S, 0x1F },
            { KEY.T, 0x14 },
            { KEY.U, 0x16 },
            { KEY.V, 0x2F },
            { KEY.W, 0x11 },
            { KEY.X, 0x2D },
            { KEY.Y, 0x15 },
            { KEY.Z, 0x2C },
            { KEY.LWIN,0x5B },
            { KEY.RWIN,0x5C },
            { KEY.APPS,
            { KEY.SLEEP,
            { KEY.NUMPAD0, 0x52 },
            { KEY.NUMPAD1, 0x4F },
            { KEY.NUMPAD2, 0x50 },
            { KEY.NUMPAD3, 0x51 },
            { KEY.NUMPAD4, 0x4B },
            { KEY.NUMPAD5, 0x4C },
            { KEY.NUMPAD6, 0x4D },
            { KEY.NUMPAD7, 0x47 },
            { KEY.NUMPAD8, 0x48 },
            { KEY.NUMPAD9, 0x49 },
            { KEY.MULTIPLY, 0x37 },
            { KEY.ADD, 0x4E },
            { KEY.SEPARATOR,
            { KEY.SUBTRACT, 0x4A },
            { KEY.DECIMAL,
            { KEY.DIVIDE,
            { KEY.F1, 0x3B },
            { KEY.F2, 0x3C },
            { KEY.F3, 0x3D },
            { KEY.F4, 0x3E },
            { KEY.F5, 0x3F },
            { KEY.F6, 0x40 },
            { KEY.F7, 0x41 },
            { KEY.F8, 0x42 },
            { KEY.F9, 0x43 },
            { KEY.F10, 0x44 },
            { KEY.F11, 0x57 },
            { KEY.F12, 0x58 },
            { KEY.F13,
            { KEY.F14,
            { KEY.F15,
            { KEY.F16,
            { KEY.F17,
            { KEY.F18,
            { KEY.F19,
            { KEY.F20,
            { KEY.F21,
            { KEY.F22,
            { KEY.F23,
            { KEY.F24,
            { KEY.NUMLOCK, 0x45 },
            { KEY.SCROLLLOCK, 0x46
            { KEY.LSHIFT, 0x2A },
            { KEY.RSHIFT, 0x36 },
            { KEY.LCONTROL,
            { KEY.RCONTROL,
            { KEY.LALT, 0x38 },
            { KEY.RALT, 0x38 },
            { KEY.BROWSERBACK,
            { KEY.BROWSERFORWARD,
            { KEY.BROWSERREFRESH,
            { KEY.BROWSERSTOP,
            { KEY.BROWSERSEARCH,
            { KEY.BROWSERFAVORITES,
            { KEY.BROWSERHOME,
            { KEY.VOLUMEMUTE,
            { KEY.VOLUMEDOWN,
            { KEY.VOLUMEUP,
            { KEY.NEXTTRACK,
            { KEY.PREVIOUSTRACK,
            { KEY.STOPMEDIA,
            { KEY.PLAYPAUSEMEDIA,
            { KEY.MAIL,
            { KEY.MEDIASELECT,
            { KEY.APP1,
            { KEY.APP2,
            { KEY.PLUS,
            { KEY.COMMA, 0x33 },
            { KEY.MINUS,
            { KEY.DOT, 0x34 },
            { KEY.PACKET,
            { KEY.ATTN,
            { KEY.CRSEL,
            { KEY.EXSEL,
            { KEY.ERASEEOF,
            { KEY.PLAY,
            { KEY.ZOOM,
            { KEY.PA1,
            { KEY.OEMCLEAR
        };

        static Dictionary<KEY, byte> scan_break = new Dictionary<KEY, byte>()
        {
            { KEY.LMOUSE,
            { KEY.RMOUSE,
            { KEY.CANCEL,
            { KEY.MMOUSE,
            { KEY.X1MOUSE,
            { KEY.X2MOUSE,
            { KEY.BACKSPACE,
            { KEY.TAB,
            { KEY.CLEAR,
            { KEY.RETURN,
            { KEY.SHIFT,
            { KEY.CONTROL,
            { KEY.ALT,
            { KEY.PAUSE,
            { KEY.CAPSLOCK,
            { KEY.ESCAPE, 0x54 },
            { KEY.SPACEBAR,
            { KEY.PAGEUP,
            { KEY.END, 0xE0 },
            { KEY.HOME, 0xE0 },
            { KEY.LEFT,
            { KEY.UP,
            { KEY.RIGHT,0xE0 },
            { KEY.DOWN,0xE0 },
            { KEY.SELECT,
            { KEY.PRINT, 0x54 },
            { KEY.PRINTSCREEN, 0xE0 },
            { KEY.INSERT,0xE0 },
            { KEY.DELETE,0xE0
            { KEY.HELP,
            { KEY.ZERO, 0 },
            { KEY.ONE, 0 },
            { KEY.TWO, 0 },
            { KEY.THREE, 0 },
            { KEY.FOUR, 0 },
            { KEY.FIVE, 0 },
            { KEY.SIX, 0 },
            { KEY.SEVEN, 0 },
            { KEY.EIGHT, 0 },
            { KEY.NINE, 0 },
            { KEY.A, 0 },
            { KEY.B, 0 },
            { KEY.C, 0 },
            { KEY.D, 0 },
            { KEY.E, 0 },
            { KEY.F, 0 },
            { KEY.G, 0 },
            { KEY.H, 0 },
            { KEY.I, 0 },
            { KEY.J, 0 },
            { KEY.K, 0 },
            { KEY.L, 0 },
            { KEY.M, 0 },
            { KEY.N, 0 },
            { KEY.O, 0 },
            { KEY.P, 0 },
            { KEY.Q, 0 },
            { KEY.R, 0 },
            { KEY.S, 0 },
            { KEY.T, 0 },
            { KEY.U, 0 },
            { KEY.V, 0 },
            { KEY.W, 0 },
            { KEY.X, 0 },
            { KEY.Y, 0 },
            { KEY.Z, 0 },
            { KEY.LWIN,0xE0
            { KEY.RWIN,0xE0
            { KEY.APPS,
            { KEY.SLEEP,
            { KEY.NUMPAD0, 0 },
            { KEY.NUMPAD1, 0 },
            { KEY.NUMPAD2, 0 },
            { KEY.NUMPAD3, 0 },
            { KEY.NUMPAD4, 0 },
            { KEY.NUMPAD5, 0 },
            { KEY.NUMPAD6, 0 },
            { KEY.NUMPAD7, 0 },
            { KEY.NUMPAD8, 0 },
            { KEY.NUMPAD9, 0 },
            { KEY.MULTIPLY,
            { KEY.ADD,
            { KEY.SEPARATOR,
            { KEY.SUBTRACT,
            { KEY.DECIMAL,
            { KEY.DIVIDE,
            { KEY.F1, 0 },
            { KEY.F2, 0 },
            { KEY.F3, 0 },
            { KEY.F4, 0 },
            { KEY.F5, 0 },
            { KEY.F6, 0 },
            { KEY.F7, 0 },
            { KEY.F8, 0 },
            { KEY.F9, 0 },
            { KEY.F10, 0
            { KEY.F11, 0
            { KEY.F12,
            { KEY.F13,
            { KEY.F14,
            { KEY.F15,
            { KEY.F16,
            { KEY.F17,
            { KEY.F18,
            { KEY.F19,
            { KEY.F20,
            { KEY.F21,
            { KEY.F22,
            { KEY.F23,
            { KEY.F24,
            { KEY.NUMLOCK,
            { KEY.SCROLLLOCK,
            { KEY.LSHIFT,
            { KEY.RSHIFT,
            { KEY.LCONTROL,
            { KEY.RCONTROL,
            { KEY.LALT,
            { KEY.RALT,
            { KEY.BROWSERBACK,
            { KEY.BROWSERFORWARD,
            { KEY.BROWSERREFRESH,
            { KEY.BROWSERSTOP,
            { KEY.BROWSERSEARCH,
            { KEY.BROWSERFAVORITES,
            { KEY.BROWSERHOME,
            { KEY.VOLUMEMUTE,
            { KEY.VOLUMEDOWN,
            { KEY.VOLUMEUP,
            { KEY.NEXTTRACK,
            { KEY.PREVIOUSTRACK,
            { KEY.STOPMEDIA,
            { KEY.PLAYPAUSEMEDIA,
            { KEY.MAIL,
            { KEY.MEDIASELECT,
            { KEY.APP1,
            { KEY.APP2,
            { KEY.PLUS,
            { KEY.COMMA, 0
            { KEY.MINUS,
            { KEY.DOT, 0
            { KEY.PACKET,
            { KEY.ATTN,
            { KEY.CRSEL,
            { KEY.EXSEL,
            { KEY.ERASEEOF,
            { KEY.PLAY,
            { KEY.ZOOM,
            { KEY.PA1,
            { KEY.OEMCLEAR
        };

        public static void keydown(KEY key) => keybd_event(vk[key], scan_make[key], 0x1, 0);

        public static void keysdown(KEY[] keys)
        {
            foreach (KEY k in keys)
                keydown(k);
        }

        public static void keysdown(List<KEY> keys) => keysdown(keys.ToArray());

        public static void keyup(KEY key) => keybd_event(vk[key], scan_break[key], 0x1 | 0x2, 0);

        public static void keysup(KEY[] keys)
        {
            foreach (KEY k in keys)
                keyup(k);
        }

        public static void keysup(List<KEY> keys) => keysup(keys.ToArray());

        public static void keystroke(KEY key)
        {
            keydown(key);
            keyup(key);
        }

        public static void keystrokes(KEY[] keys)
        {
            foreach (KEY k in keys)
                keystroke(k);
        }

        public static void keystrokes(List<KEY> keys) => keystrokes(keys.ToArray());

        public static bool key_pressed(KEY key)
        {
            byte[] keys = new byte[256];

            if (!GetKeyboardState(keys))
                throw new Win32Exception(Marshal.GetLastWin32Error());

            return (keys[vk[key]] & 0x80) != 0;
        }

        [DllImport("user32.dll")]
        static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, uint dwExtraInfo);

        [DllImport("User32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        static extern bool GetKeyboardState(byte[] lpKeyState);
    }
}
